version: '3.8'

services:
  # PostgreSQL Database for Development
  database:
    image: postgres:15-alpine
    container_name: insurance-crm-db-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: insurance_crm_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for Session Storage (Optional)
  redis:
    image: redis:7-alpine
    container_name: insurance-crm-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres_dev_data:
    driver: local
  redis_dev_data:
    driver: local

networks:
  default:
    name: insurance-crm-dev-network